version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: pastebin-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: pastebin-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/pastebin
      - JWT_SECRET=pastebin_production_jwt_secret_key_2026
    depends_on:
      - mongodb

volumes:
  mongo-data:
